server:
  port: 8888
  servlet:
    application-display-name: contentStorage


spring:
  datasource:
    type: org.apache.commons.dbcp2.BasicDataSource
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:data/storage.db
    dbcp2:
      max-idle: 50
      max-total: 2000
      min-idle: 10

  jpa:
    database-platform: cc.ayakurayuki.contentstorage.common.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: false

  thymeleaf:
    enabled: true
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    cache: false
    servlet:
      content-type: text/html

  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true


logging:
  file: logs/csa.log
  path: logs
